#include "ijkavutil/ijkutils.h"
#include "libavutil/error.h"
#include "ff_fferror.h"

int ff_err2cypress_err(int err) {

    switch (err) {
    case AVERROR(ENOMEM):
        return CYPRESS_PLAYER_ERROR_NOMEM;
    case AVERROR(EACCES):
        return CYPRESS_PLAYER_ERROR_IO_FILE_ACCESS_FAILED;
    case AVERROR(ENOENT):
        return CYPRESS_PLAYER_ERROR_IO_FILE_NOT_FOUND;
    case AVERROR(EINVAL):
        return CYPRESS_PLAYER_ERROR_INVALID_ARG;
    case AVERROR(EIO):
        return CYPRESS_PLAYER_ERROR_IO;
    case AVERROR_INVALIDDATA:
        return CYPRESS_PLAYER_ERROR_INVALID_DATA;
    case AVERROR_STREAM_NOT_FOUND:
        return CYPRESS_PLAYER_ERROR_STREAM_NO_PLAYABLE_AV;
    case AVERROR_DEMUXER_NOT_FOUND:
        return CYPRESS_PLAYER_ERROR_DEMUXER_NOT_FOUND;

    case AVERROR_HTTP_BAD_REQUEST:
        return CYPRESS_PLAYER_ERROR_IO_HTTP_BAD_REQUEST;
    case AVERROR_HTTP_UNAUTHORIZED:
        return CYPRESS_PLAYER_ERROR_IO_HTTP_UNAUTHORIZED;
    case AVERROR_HTTP_FORBIDDEN:
        return CYPRESS_PLAYER_ERROR_IO_HTTP_FORBIDDEN;
    case AVERROR_HTTP_NOT_FOUND:
        return CYPRESS_PLAYER_ERROR_IO_HTTP_NOT_FOUND;
    case AVERROR_HTTP_OTHER_4XX:
        return CYPRESS_PLAYER_ERROR_IO_HTTP_OTHER_4XX;
    case AVERROR_HTTP_SERVER_ERROR:
        return CYPRESS_PLAYER_ERROR_IO_HTTP_SERVER_ERROR;

    case AVERROR_PROTOCOL_NOT_FOUND:
        return CYPRESS_PLAYER_ERROR_IO_PROTOCOL_NOT_FOUND;

    default:
        return CYPRESS_PLAYER_ERROR_UNKNOWN;
    }
}


